name: Build electron

on:
  workflow_dispatch: # allows manual trigger

jobs:
  build-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          node -v
          npm -v

      - name: Git clone and build
        run: |
          git clone --recursive https://github.com/Gzh0821/pvzge_web.git
          npm install
          npm run build:linux -- --publish=never
        env:
          GH_TOKEN: ""

      - name: Upload release folder
        uses: actions/upload-artifact@v4
        with:
          name: pvzge-linux-release
          path: pvzge_web/release
